---
- name: Make monicahq directory.
  file:
    path: "{{ volumes_root }}/monicahq"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy monicahq docker-compose.yml file into place.
  template:
    src: docker-compose.monicahq.yml.j2
    dest: "{{ volumes_root }}/monicahq/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Copy monicahq .env file into place.
  template:
    src: monicahq.env.j2
    dest: "{{ volumes_root }}/monicahq/monicahq.env"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    monicahq_db_password: "{{lookup('password', './settings/passwords/monicahq_db_password chars=ascii_letters')}}"
  become: yes

- name: Configure monicahq systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/monicahq.service

- name: Start monicahq
  systemd:
    name: monicahq
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
