---
- name: Make photoprism directory.
  file:
    path: "{{ volumes_root }}/photoprism"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy photoprism docker-compose.yml file into place.
  template:
    src: docker-compose.photoprism.yml.j2
    dest: "{{ volumes_root }}/photoprism/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure photoprism systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/photoprism.service

- name: Start photoprism
  systemd:
    name: photoprism
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
