---
- name: Make openldap directory.
  file:
    path: "{{ volumes_root }}/openldap"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy openldap docker-compose.yml file into place.
  template:
    src: docker-compose.openldap.yml.j2
    dest: "{{ volumes_root }}/openldap/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure openldap systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/openldap.service

- name: Start openldap
  systemd:
    name: openldap
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
