---
- name: Make taisun directory.
  file:
    path: "{{ volumes_root }}/taisun"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy taisun docker-compose.yml file into place.
  template:
    src: docker-compose.taisun.yml.j2
    dest: "{{ volumes_root }}/taisun/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure taisun systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/taisun.service

- name: Start taisun
  systemd:
    name: taisun
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
