---
- name: Stop specified service
  systemd:
    name: "{{ service_item }}"
    enabled: no
    daemon-reload: no
    state: stopped

- name: Create docker-compose.override.yml
  copy:
    src: "{{ volumes_root }}/{{ service_item }}/docker-compose.yml"
    dest: "{{ volumes_root }}/{{ service_item }}/docker-compose.override.yml"
    remote_src: yes
    mode: preserve
    force: no

- name: Start specified service
  systemd:
    name: "{{ service_item }}"
    enabled: yes
    daemon-reload: yes
    state: started
