---
- name: Stop specified service
  systemd:
    name: "{{ service_item }}"
    enabled: no
    daemon-reload: yes
    state: stopped

- name: Create docker-compose.override.yml
  copy:
    src: "docker-compose.{{ service_item }}.yml"
    dest: "settings/{{ config_dir }}/override/{{ service_item }}/docker-compose.override.yml"
    mode: preserve
    force: no

- name: Start specified service
  systemd:
    name: "{{ service_item }}"
    enabled: yes
    daemon-reload: yes
    state: started
