---
- name: Make healthchecks directory.
  file:
    path: "{{ volumes_root }}/healthchecks"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy healthchecks docker-compose.yml file into place.
  template:
    src: docker-compose.healthchecks.yml.j2
    dest: "{{ volumes_root }}/healthchecks/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure healthchecks systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/healthchecks.service

- name: Start healthchecks
  systemd:
    name: healthchecks
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
