---
- name: Make factorio directory.
  file:
    path: "{{ volumes_root }}/factorio"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy factorio docker-compose.yml file into place.
  template:
    src: docker-compose.factorio.yml.j2
    dest: "{{ volumes_root }}/factorio/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure factorio systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/factorio.service

- name: Start factorio
  systemd:
    name: factorio
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
