---
- name: Make adguard directories
  file:
    path: "{{ volumes_root }}/{{item}}"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  loop:
    - "adguardhome/work"
    - "adguardhome/config"
  become: yes

- name: Copy adguardhome docker-compose.yml file into place.
  template:
    src: docker-compose.adguardhome.yml.j2
    dest: "{{ volumes_root }}/adguardhome/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Install bCrypt
  command: >
    pip install bcrypt

- name: Generate bCrypt password hash
  command: >
    python -c 'from passlib.hash import bcrypt; print(bcrypt.hash("{{ default_password }}"))'
  register: passwrd

- name: Copy adguardhome config file into place.
  template:
    src: AdGuardHome.j2
    dest: "{{ volumes_root }}/adguardhome/config/AdGuardHome.yaml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    password: "{{passwrd.stdout}}"
  become: yes

- name: Configure adguardhome systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/adguardhome.service

- name: Reconfigure Systemd-resolved
  include_role:
    name: vivumlab_systemd-resolve

- name: Start adguardhome
  systemd:
    name: adguardhome
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
