---
- name: Make paperless directory.
  file:
    path: "{{ volumes_root }}/paperless"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy paperless docker-compose.yml file into place.
  template:
    src: docker-compose.paperless.yml.j2
    dest: "{{ volumes_root }}/paperless/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure paperless systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/paperless.service

- name: Start paperless
  systemd:
    name: paperless
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
