---
- name: Make jellyfin directory.
  file:
    path: "{{ volumes_root }}/jellyfin"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy jellyfin docker-compose.yml file into place.
  template:
    src: docker-compose.jellyfin.yml.j2
    dest: "{{ volumes_root }}/jellyfin/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure jellyfin systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/jellyfin.service

- name: Start jellyfin
  systemd:
    name: jellyfin
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
