---
- name: Make folding_at_home directory.
  file:
    path: "{{ volumes_root }}/folding_at_home"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy folding_at_home docker-compose.yml file into place.
  template:
    src: docker-compose.folding_at_home.yml.j2
    dest: "{{ volumes_root }}/folding_at_home/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  Become: yes

- name: Configure folding_at_home systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/folding_at_home.service

- name: Start folding_at_home
  systemd:
    name: folding_at_home
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
