---

repos:
  - repo: local
    hooks:
      - id: check-not-translated
        name: Check for missing I18n after puts or say
        description: This hook checks for missing I18n after puts or say.
        entry: scripts/check_not_translated.sh
        language: script
        files: \.rb$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: no-commit-to-branch
        args: [--branch, dev, --branch, master]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.25.0
    hooks:
      - id: yamllint
        args: [-c=yamllint.conf]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.13.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg

exclude: 'docker/motd|vendor'
