# travis.yml
language: ruby
os: linux
dist: xenial


stages:
  - pre-commit
  - name: master
    if: branch = master
  - deploy docs

jobs:
  include:
    - language: python
      python: 3.8
      stage: pre-commit
      script: pre-commit run --all-files
      name: "Pre-commit run"
      install:
        - pip3 install pre-commit
    - language: node_js
      node_js: node
      stage: master
      name: "Master commitlint"
      script:
        - commitlint-travis
    - language: python
      python: 3.8
      stage: deploy docs
      install:
        - pip3 install mkdocs
        - pip3 install mkdocs-material
        - pip3 install mkdocs-git-revision-date-localized-plugin
      script: mkdocs build --verbose --clean --strict
      name: "Deploy MKDocs to GH-Pages"
      deploy:
        fqdn: docs.vivumlab.com
        strategy: git
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
        local_dir: site
        on:
          branch: master

cache:
  directories:
    - $HOME/.cache/pre-commit
