---
- hosts: all
  gather_facts: no
  tags: setup

  tasks:
    - name: Stop services
      systemd:
        name: "{{ service_item }}"
        state: stopped
      when: query == true
      loop: "{{ services | flatten(1) }}"
      loop_control:
        loop_var: service_item
      vars:
        query: "{{ service_item + '.enable' }}"
      become: yes
