---
- hosts: all
  gather_facts: no

  tasks:
    - name: Stop services
      systemd:
        name: "{{ service_item }}.service"
        state: stopped
        no_block: true
      when: query | bool
      loop: "{{ services | flatten(1) }}"
      loop_control:
        loop_var: service_item
      vars:
        query: "{{ vars[service_item]['enable'] }}"
      become: yes
