---
- name: customize service
  hosts: vivumlab
  gather_facts: no
  tags: serviceedit
  pre_tasks:
    - name: Wait for connection if not available, timeout 600 seconds
      wait_for_connection:
        timeout: 600
        delay: 0
      when: wait_for_connection == true

  roles:
    - vivumlab_service-edit
