---
# Initial setup so Ansible can actually work.
- name: Install python (required by Ansible).
  gather_facts: no
  hosts: all
  become: yes
  become_method: sudo
  any_errors_fatal: true
  pre_tasks:
    - name: Wait for connection if not available, timeout 600 seconds
      wait_for_connection:
        timeout: 600
        delay: 0
      when: wait_for_connection == true

# Restore VivumLab from the most recent backup.
- hosts: all
  gather_facts: no
  tags:
    - setup
    - restore
  pre_tasks:
    - name: Wait for connection if not available, timeout 600 seconds
      wait_for_connection:
        timeout: 600
        delay: 0
      when: wait_for_connection == true

  roles:
    - vivumlab_setup
    - vivumlab_restore
