---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no

  tasks:
    - name: Copy docs md files into place
      template:
        src: "{{ item.src }}"
        dest: "{{ playbook_dir }}/docs/{{ item.path }}"
      with_filetree: docs/
      when: item.state == 'file' and (item.path | basename | regex_search('(.md)'))

    - name: Copy docs other files into place
      copy:
        src: "{{ item.src }}"
        dest: "{{ playbook_dir }}/docs/{{ item.path }}"
      with_filetree: docs/
      when: item.state == 'file' and (item.path | basename | regex_search('[^\.md]*$'))
...
