---
- hosts: 127.0.0.1
  connection: local
  vars_prompt:
    - name: vlab_ip
      prompt: |+

        ======== REMOTE SSH IP ========
        Allows VivumLab to communicate with the remote machine.
        required: yes
        default: none

        Currently VivumLab only supports IPv4 addresses.

        Enter the remote machines IP address
      private: no
      #
    - name: vlab_port
      prompt: |+

        ======== REMOTE SSH PORT ========
        Allows VivumLab to communicate via a non-default SSH port.
        required: no
        default: 22

        It is good security practise to change the default SSH port.
        VivumLab DOES NOT set a custom port for you; No input sets the default.


        Enter the custom SSH port
      private: no
      default: 22

    - name: vlab_ssh_user
      prompt: |+

        ======== REMOTE SSH USER ========
        Enables VivumLab to use the user with SSH permissions on the remote machine.
        required: no
        default: root

        VivumLab strongly advises against using the 'root' account for SSH connections.
        No input sets the default.

        Enter your remote machines SSH username
      private: no
      default: root

    - name: ansible_become_password
      prompt: |+

        ======== REMOTE SSH PASSWORD ========
        Required for VivumLab to use the user with SSH permissions on the remote machine.
        required: yes
        default: none

        The password for the user with SSH permissions is required for administrative actions.

        Enter your remote machines SSH password
      unsafe: yes
      private: yes

    - name: passwordless_sshkey
      prompt: |+

        ======== PASSWORDLESS SSH KEY ========
        Allows VivumLab to access the remote machine via passwordless SSH keys.
        required: no
        default: id_rsa

        SSH keys provide great security benefits; prferably 'passwordless' for ease of use.
        VivumLab currently does not support 'passworded' SSH keys.
        No input sets the default.

        Enter the name of your personalised passwordless ssh keys
      private: no
      default: "id_rsa"

    - name: default_username
      prompt: |+

        ======== DEFAULT SERVICE ADMIN USERNAME ========
        Sets a default admin username, to be used for applicable deployed services.
        required: no
        default: admin

        Not all VivumLab deployed services will set up an administrator account for the user.
        No input sets the default.

        Enter the default 'admin' username
      private: no
      default: admin

    - name: default_password
      prompt: |+

        ======== DEFAULT SERVICE ADMIN PASSWORD ========
        Sets a default admin password, to be used for applicable deployed services.
        required: no
        default: none

        Please ensure that this is only a 'placeholder' password, to gain initial access to the
        admin account of an applicable service, as some services may store this password in plain text

        Enter the default 'admin' password
      unsafe: yes
      private: yes

    - name: domain
      prompt: |+

        ======== DOMAIN NAME ========
        Sets the domain that VivumLab deployed services will accessable on.
        required: yes
        default: localhost

        Please ensure that you have access to the domain, and that all required information has
        been completed with your domain registrar, eg. A record
        Be sure to fill the complete address, including any domain extensions, eg.
        - yourdomain.com.au
        - helloworld.org
        - vivumlab.it
        No input sets the default.

        Enter the desired domain name
      private: no
      default: localhost

    - name: admin_email
      prompt: |+

        ======== VIVUMLAB USER EMAIL ========
        Sets the users desired email for use with VivumLab.
        required: yes
        default: none

        VivumLab provides HTTPS as default; By todays web standards HTTPS is both achievable,
        and a minimal requirement.
        Not providing a valid email address, will break letsencrypt/HTTPS functionality.

        Enter the desired email address
      private: no

  roles:
    - vivumlab_config
