---
- name: Make watchtower directory.
  file:
    path: "{{ volumes_root }}/watchtower"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy watchtower docker-compose.yml file into place.
  template:
    src: docker-compose.watchtower.yml.j2
    dest: "{{ volumes_root }}/watchtower/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure watchtower systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/watchtower.service

- name: Start watchtower
  systemd:
    name: watchtower
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
