---
- name: Make focalboard directory.
  file:
    path: "{{ volumes_root }}/focalboard"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy focalboard docker-compose.yml file into place.
  template:
    src: docker-compose.focalboard.yml.j2
    dest: "{{ volumes_root }}/focalboard/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure focalboard systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/focalboard.service
  become: yes

- name: Start focalboard
  systemd:
    name: focalboard
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
