---
- name: Make code-server directories.
  file:
    path: "{{ volumes_root }}/codeserver/{{ item }}"
    state: directory
    mode: 0777
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  loop:
    - ".local"
    - "project"
  become: yes

- name: Copy code-server docker-compose.yml file into place.
  template:
    src: docker-compose.codeserver.yml.j2
    dest: "{{ volumes_root }}/codeserver/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure code-server systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/codeserver.service

- name: Start code-server
  systemd:
    name: codeserver
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
