---
- name: Make apache2 directory.
  file:
    path: "{{ volumes_root }}/apache2"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy apache2 docker-compose.yml file into place.
  template:
    src: docker-compose.apache2.yml.j2
    dest: "{{ volumes_root }}/apache2/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure apache2 systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/apache2.service

- name: Start apache2
  systemd:
    name: apache2
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
