---
- name: Make LibrePhotos directory.
  file:
    path: "{{ volumes_root }}/librephotos/{{ item }}"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  loop:
    - "thumbnails"
    - "logs"
  become: yes

- name: Make LibrePhotos DB directory
  file:
    path: "{{ volumes_root }}/librephotos/db"
    state: directory

- name: Copy LibrePhotos docker-compose.yml file into place.
  template:
    src: docker-compose.librephotos.yml.j2
    dest: "{{ volumes_root }}/librephotos/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure LibrePhotos systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/librephotos.service

- name: Start Librephotos
  systemd:
    name: librephotos
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
