---
- name: Make piwigo directory.
  file:
    path: "{{ volumes_root }}/piwigo"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy piwigo docker-compose.yml file into place.
  template:
    src: docker-compose.piwigo.yml.j2
    dest: "{{ volumes_root }}/piwigo/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure piwigo systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/piwigo.service

- name: Start piwigo
  systemd:
    name: piwigo
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
