---
- name: Make guacamole directory.
  file:
    path: "{{ volumes_root }}/guacamole"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy guacamole docker-compose.yml file into place.
  template:
    src: docker-compose.guacamole.yml.j2
    dest: "{{ volumes_root }}/guacamole/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure guacamole systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/guacamole.service

- name: Start guacamole
  systemd:
    name: guacamole
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
