---
- name: Make samba directory.
  file:
    path: "{{ volumes_root }}/samba"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy samba docker-compose.yml file into place.
  template:
    src: docker-compose.samba.yml.j2
    dest: "{{ volumes_root }}/samba/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure samba systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/samba.service

- name: Start samba
  systemd:
    name: samba
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
