---
- name: Make minecraft directory.
  file:
    path: "{{ volumes_root }}/minecraft"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy minecraft docker-compose.yml file into place.
  template:
    src: docker-compose.minecraft.yml.j2
    dest: "{{ volumes_root }}/minecraft/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  becom: yes

- name: Configure minecraft systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/minecraft.service

- name: Start minecraft
  systemd:
    name: minecraft
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
