---
- name: Make sickchill directory.
  file:
    path: "{{ volumes_root }}/sickchill"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy sickchill docker-compose.yml file into place.
  template:
    src: docker-compose.sickchill.yml.j2
    dest: "{{ volumes_root }}/sickchill/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure sickchill systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/sickchill.service

- name: Start sickchill
  systemd:
    name: sickchill
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
