---
- name: Make teedy directory.
  file:
    path: "{{ volumes_root }}/teedy"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy teedy docker-compose.yml file into place.
  template:
    src: docker-compose.teedy.yml.j2
    dest: "{{ volumes_root }}/teedy/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure teedy systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/teedy.service

- name: Start teedy
  systemd:
    name: teedy
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
