---
- name: Make lidarr directory.
  file:
    path: "{{ volumes_root }}/lidarr"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy lidarr docker-compose.yml file into place.
  template:
    src: docker-compose.lidarr.yml.j2
    dest: "{{ volumes_root }}/lidarr/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  beome: yes

- name: Configure lidarr systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/lidarr.service

- name: Start lidarr
  systemd:
    name: lidarr
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
