---
- name: Make zammad directory.
  file:
    path: "{{ volumes_root }}/zammad/{{ item }}"
    state: directory
    mode: 0777
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  loop:
    - "zammad-data"
    - "postgresql-data"
    - "elasticsearch-data"
    - "zammad-backup"
  become: yes

- name: Copy zammad docker-compose.yml file into place.
  template:
    src: docker-compose.zammad.yml.j2
    dest: "{{ volumes_root }}/zammad/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure zammad systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/zammad.service

- name: Start zammad
  systemd:
    name: zammad
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
