---
- name: Make digikam directory.
  file:
    path: "{{ volumes_root }}/digikam"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy digikam docker-compose.yml file into place.
  template:
    src: docker-compose.digikam.yml.j2
    dest: "{{ volumes_root }}/digikam/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure digikam systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/digikam.service

- name: Start digikam
  systemd:
    name: digikam
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
