---
- name: Make simply_shorten directory.
  file:
    path: "{{ volumes_root }}/simply_shorten"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy simply_shorten docker-compose.yml file into place.
  template:
    src: docker-compose.simply_shorten.yml.j2
    dest: "{{ volumes_root }}/simply_shorten/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure simply_shorten systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/simply_shorten.service

- name: Start simply_shorten
  systemd:
    name: simply_shorten
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
