---
- name: Make massivedecks directory.
  file:
    path: "{{ volumes_root }}/massivedecks"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy massivedecks docker-compose.yml file into place.
  template:
    src: docker-compose.massivedecks.yml.j2
    dest: "{{ volumes_root }}/massivedecks/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure massivedecks systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/massivedecks.service

- name: Start massivedecks
  systemd:
    name: massivedecks
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
