---
- name: Make mailu directory.
  file:
    path: "{{ volumes_root }}/mailu"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy mailu docker-compose.yml file into place.
  template:
    src: docker-compose.mailu.yml.j2
    dest: "{{ volumes_root }}/mailu/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Copy mailu configuration file into place.
  template:
    src: mailu.env.j2
    dest: "{{ volumes_root }}/mailu/.env"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Configure mailu systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/mailu.service

- name: Start mailu
  systemd:
    name: mailu
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
