---
- name: Make poli directory.
  file:
    path: "{{ volumes_root }}/poli"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy poli docker-compose.yml file into place.
  template:
    src: docker-compose.poli.yml.j2
    dest: "{{ volumes_root }}/poli/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure poli systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/poli.service

- name: Start poli
  systemd:
    name: poli
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
