---
- name: Make elkstack directory.
  file:
    path: "{{ volumes_root }}/elkstack"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: set vm page size
  shell: sysctl -w vm.max_map_count=262144
  become: yes

- name: Copy elkstack docker-compose.yml file into place.
  template:
    src: docker-compose.elkstack.yml.j2
    dest: "{{ volumes_root }}/elkstack/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure elkstack systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/elkstack.service

- name: Start elkstack
  systemd:
    name: elkstack
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
