---
- name: Make ubooquity directory.
  file:
    path: "{{ volumes_root }}/ubooquity"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy ubooquity docker-compose.yml file into place.
  template:
    src: docker-compose.ubooquity.yml.j2
    dest: "{{ volumes_root }}/ubooquity/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure ubooquity systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/ubooquity.service

- name: Start ubooquity
  systemd:
    name: ubooquity
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
