---
- name: Make tautulli directory.
  file:
    path: "{{ volumes_root }}/tautulli"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy tautulli docker-compose.yml file into place.
  template:
    src: docker-compose.tautulli.yml.j2
    dest: "{{ volumes_root }}/tautulli/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure tautulli systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/tautulli.service

- name: Start tautulli
  systemd:
    name: tautulli
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
