---
- name: Make shinobi directory.
  file:
    path: "{{ volumes_root }}/shinobi"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy shinobi docker-compose.yml file into place.
  template:
    src: docker-compose.shinobi.yml.j2
    dest: "{{ volumes_root }}/shinobi/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure shinobi systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/shinobi.service

- name: Start shinobi
  systemd:
    name: shinobi
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
