---
- name: Make restic directory.
  file:
    path: "{{ volumes_root }}/restic"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy restic docker-compose.yml file into place.
  template:
    src: docker-compose.restic.yml.j2
    dest: "{{ volumes_root }}/restic/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure restic systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/restic.service

- name: Start restic
  systemd:
    name: restic
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
