---
- name: Make airsonic directory.
  file:
    path: "{{ volumes_root }}/airsonic"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy airsonic docker-compose.yml file into place.
  template:
    src: docker-compose.airsonic.yml.j2
    dest: "{{ volumes_root }}/airsonic/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure airsonic systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/airsonic.service

- name: Start airsonic
  systemd:
    name: airsonic
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
