---
- name: Make bookstack directory.
  file:
    path: "{{ volumes_root }}/bookstack"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Make uploads directories.
  file:
    path: "{{ volumes_root }}/bookstack/{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  loop:
    - "uploads"
    - "storage-uploads"
  become: yes

- name: Copy bookstack docker-compose.yml file into place.
  template:
    src: docker-compose.bookstack.yml.j2
    dest: "{{ volumes_root }}/bookstack/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure bookstack systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/bookstack.service

- name: Start bookstack
  systemd:
    name: bookstack
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
