---
- name: Create necessary folders, with appropriate permissions.
  file:
    path: "{{ volumes_root }}/nextcloud/{{ item }}"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  with_items:
    - "config"
    - "custom_apps"
    - "themes"
  become: yes

- name: Copy nextcloud docker-compose.yml file into place.
  template:
    src: docker-compose.nextcloud.yml.j2
    dest: "{{ volumes_root }}/nextcloud/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure nextcloud systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/nextcloud.service

- name: Start nextcloud
  systemd:
    name: nextcloud
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
