---
- name: Make tick directory.
  file:
    path: "{{ volumes_root }}/tick"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy tick docker-compose.yml file into place.
  template:
    src: docker-compose.tick.yml.j2
    dest: "{{ volumes_root }}/tick/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure telegraf
  template:
    src: telegraf.conf.j2
    dest: "{{ volumes_root }}/tick/telegraf.conf"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Configure tick systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/tick.service

- name: Start tick
  systemd:
    name: tick
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
