---
- name: Make airbyte directory.
  file:
    path: "{{ volumes_root }}/airbyte"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy airbyte docker-compose.yml file into place.
  template:
    src: docker-compose.airbyte.yml.j2
    dest: "{{ volumes_root }}/airbyte/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure airbyte systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/airbyte.service
  become: yes

- name: Start airbyte
  systemd:
    name: airbyte
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
