---
- name: Make barcodebuddy directory.
  file:
    path: "{{ volumes_root }}/barcodebuddy"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy barcodebuddy docker-compose.yml file into place.
  template:
    src: docker-compose.barcodebuddy.yml.j2
    dest: "{{ volumes_root }}/barcodebuddy/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure barcodebuddy systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/barcodebuddy.service

- name: Start barcodebuddy
  systemd:
    name: barcodebuddy
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
