package_filename:
  enable: {{ package_filename.enable | default(False) }}
  https_only: {{ package_filename.https_only | default(False) }}
  auth: {{ package_filename.auth | default(False) }}
  domain: {{ package_filename.domain | default(False) }}
  subdomain: {{ package_filename.subdomain | default("package_filename") }}
  version: {{ package_filename.version | default("latest") }}
