---
- name: Make ghost directory.
  file:
    path: "{{ volumes_root }}/ghost"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy ghost docker-compose.yml file into place.
  template:
    src: docker-compose.ghost.yml.j2
    dest: "{{ volumes_root }}/ghost/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure ghost systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/ghost.service

- name: Start ghost
  systemd:
    name: ghost
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
