---
- name: Make firefly_iii directory.
  file:
    path: "{{ volumes_root }}/firefly_iii"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy firefly_iii docker-compose.yml file into place.
  template:
    src: docker-compose.firefly_iii.yml.j2
    dest: "{{ volumes_root }}/firefly_iii/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure firefly_iii systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/firefly_iii.service

- name: Start firefly_iii
  systemd:
    name: firefly_iii
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
