---
- name: Create necessary folders, with appropriate permissions.
  file:
    path: "{{ volumes_root }}/gitea/{{ item }}"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  with_items:
    - "data"
    - "config"
  become: yes

- name: Copy gitea docker-compose.yml file into place.
  template:
    src: docker-compose.gitea.yml.j2
    dest: "{{ volumes_root }}/gitea/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure gitea systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/gitea.service

- name: Start gitea
  systemd:
    name: gitea
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
