---
- name: Make funkwhale directory.
  file:
    path: "{{ volumes_root }}/funkwhale/{{ item }}"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  loop:
    - "media"
  become: yes

- name: Copy funkwhale docker-compose.yml file into place.
  template:
    src: docker-compose.funkwhale.yml.j2
    dest: "{{ volumes_root }}/funkwhale/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure funkwhale systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/funkwhale.service

- name: Start funkwhale
  systemd:
    name: funkwhale
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
