---
- name: Make organizr directory.
  file:
    path: "{{ volumes_root }}/organizr"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy organizr docker-compose.yml file into place.
  template:
    src: docker-compose.organizr.yml.j2
    dest: "{{ volumes_root }}/organizr/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure organizr systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/organizr.service

- name: Start organizr
  systemd:
    name: organizr
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
