---
- name: Make pixelfed directories.
  file:
    path: "{{ volumes_root }}/pixelfed/{{ item }}"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  with_items:
    - "storage"
    - "redis"
  become: yes

- name: Make pixelfed DB directory.
  file:
    path: "{{ volumes_root }}/pixelfed/db"
    state: directory

- name: Copy pixelfed docker-compose.yml file into place.
  template:
    src: docker-compose.pixelfed.yml.j2
    dest: "{{ volumes_root }}/pixelfed/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Copy pixelfed .env file into place.
  template:
    src: pixelfed.env.j2
    dest: "{{ volumes_root }}/pixelfed/pixelfed.env"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Configure pixelfed systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/pixelfed.service

- name: Start pixelfed
  systemd:
    name: pixelfed
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
