---
- name: Make freshrss directory.
  file:
    path: "{{ volumes_root }}/freshrss"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy freshrss docker-compose.yml file into place.
  template:
    src: docker-compose.freshrss.yml.j2
    dest: "{{ volumes_root }}/freshrss/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure freshrss systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/freshrss.service

- name: Start freshrss
  systemd:
    name: freshrss
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
