---
- name: Make drone directory.
  file:
    path: "{{ volumes_root }}/drone"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy drone docker-compose.yml file into place.
  template:
    src: docker-compose.drone.yml.j2
    dest: "{{ volumes_root }}/drone/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure drone systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/drone.service

- name: Start drone
  systemd:
    name: drone
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
