---
- name: Make mashio directory.
  file:
    path: "{{ volumes_root }}/mashio"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy mashio docker-compose.yml file into place.
  template:
    src: docker-compose.mashio.yml.j2
    dest: "{{ volumes_root }}/mashio/docker-compose.yml"
  become: yes

- name: Configure mashio systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/mashio.service

- name: Start mashio
  systemd:
    name: mashio
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
