---
- name: Make invoiceninja directories
  file:
    path: "{{ volumes_root }}/invoiceninja/{{item}}"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  loop:
    - "config/nginx/conf.d"
    - "config/php"
    - "public"
    - "logo"
    - "storage"
  become: yes

- name: install nginx config
  template:
    src: nginx.conf
    dest: "{{  volumes_root }}/invoiceninja/config/nginx/nginx.conf"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: install PHP config files
  template:
    src: php-cli.j2
    dest: "{{ volumes_root }}/invoiceninja/config/php/{{item}}"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  loop:
    - php-cli.ini
    - php.ini
  become: yes

- name: Generate new encryption key.
  shell: >
    docker run --rm -i invoiceninja/invoiceninja:{{invoiceninja.version}} php artisan key:generate --show | awk 'END{print}'
  register: application_key

- name: Copy invoiceninja docker-compose.yml file into place.
  template:
    src: docker-compose.invoiceninja.yml.j2
    dest: "{{ volumes_root }}/invoiceninja/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
    application_key: application_key
  become: yes

- name: Configure invoiceninja systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/invoiceninja.service

- name: Start invoiceninja
  systemd:
    name: invoiceninja
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
