---
- name: Make nzbget directory.
  file:
    path: "{{ volumes_root }}/nzbget"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy nzbget docker-compose.yml file into place.
  template:
    src: docker-compose.nzbget.yml.j2
    dest: "{{ volumes_root }}/nzbget/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure nzbget systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/nzbget.service

- name: Start nzbget
  systemd:
    name: nzbget
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
