---
- name: Make paperlessng directory.
  file:
    path: "{{ volumes_root }}/paperlessng"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy paperlessng docker-compose.yml file into place.
  template:
    src: docker-compose.paperlessng.yml.j2
    dest: "{{ volumes_root }}/paperlessng/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure paperlessng systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/paperlessng.service
  become: yes

- name: Start paperlessng
  systemd:
    name: paperlessng
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
