---
- name: Make matomo directory.
  file:
    path: "{{ volumes_root }}/matomo"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy matomo docker-compose.yml file into place.
  template:
    src: docker-compose.matomo.yml.j2
    dest: "{{ volumes_root }}/matomo/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure matomo systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/matomo.service

- name: Start matomo
  systemd:
    name: matomo
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
