---
- name: Make bulletnotes directory.
  file:
    path: "{{ volumes_root }}/bulletnotes"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy bulletnotes docker-compose.yml file into place.
  template:
    src: docker-compose.bulletnotes.yml.j2
    dest: "{{ volumes_root }}/bulletnotes/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure bulletnotes systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/bulletnotes.service

- name: Start bulletnotes
  systemd:
    name: bulletnotes
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
