---
- name: Make ethercalc directory.
  file:
    path: "{{ volumes_root }}/ethercalc"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  beome: yes

- name: Copy ethercalc docker-compose.yml file into place.
  template:
    src: docker-compose.ethercalc.yml.j2
    dest: "{{ volumes_root }}/ethercalc/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure ethercalc systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/ethercalc.service

- name: Start ethercalc
  systemd:
    name: ethercalc
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
