---
- name: Make jackett directory.
  file:
    path: "{{ volumes_root }}/jackett"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy jackett docker-compose.yml file into place.
  template:
    src: docker-compose.jackett.yml.j2
    dest: "{{ volumes_root }}/jackett/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure jackett systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/jackett.service

- name: Start jackett
  systemd:
    name: jackett
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
