---
- name: Make unificontroller directory.
  file:
    path: "{{ volumes_root }}/unificontroller"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy unificontroller docker-compose.yml file into place.
  template:
    src: docker-compose.unificontroller.yml.j2
    dest: "{{ volumes_root }}/unificontroller/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure unificontroller systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/unificontroller.service

- name: Start unificontroller
  systemd:
    name: unificontroller
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
