---
- name: Make thelounge directory.
  file:
    path: "{{ volumes_root }}/thelounge"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy thelounge docker-compose.yml file into place.
  template:
    src: docker-compose.thelounge.yml.j2
    dest: "{{ volumes_root }}/thelounge/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure thelounge systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/thelounge.service

- name: Start thelounge
  systemd:
    name: thelounge
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
