---
- name: Make minio directory.
  file:
    path: "{{ volumes_root }}/minio"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy minio docker-compose.yml file into place.
  template:
    src: docker-compose.minio.yml.j2
    dest: "{{ volumes_root }}/minio/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure minio systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/minio.service

- name: Start minio
  systemd:
    name: minio
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
