---
- name: Make ombi directory.
  file:
    path: "{{ volumes_root }}/ombi"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy ombi docker-compose.yml file into place.
  template:
    src: docker-compose.ombi.yml.j2
    dest: "{{ volumes_root }}/ombi/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure ombi systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/ombi.service

- name: Start ombi
  systemd:
    name: ombi
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
