---
- name: Make huginn directory.
  file:
    path: "{{ volumes_root }}/huginn"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy huginn docker-compose.yml file into place.
  template:
    src: docker-compose.huginn.yml.j2
    dest: "{{ volumes_root }}/huginn/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure huginn systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/huginn.service

- name: Start huginn
  systemd:
    name: huginn
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
