---
- name: Make mstream directory.
  file:
    path: "{{ volumes_root }}/mstream"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy mstream docker-compose.yml file into place.
  template:
    src: docker-compose.mstream.yml.j2
    dest: "{{ volumes_root }}/mstream/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure mstream systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/mstream.service

- name: Start mstream
  systemd:
    name: mstream
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
