---
- name: Make kibitzr directory.
  file:
    path: "{{ volumes_root }}/kibitzr"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy kibitzr docker-compose.yml file into place.
  template:
    src: docker-compose.kibitzr.yml.j2
    dest: "{{ volumes_root }}/kibitzr/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure kibitzr systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/kibitzr.service

- name: Start kibitzr
  systemd:
    name: kibitzr
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
