---
- include_tasks: ubuntuinstall.yml
  when: (ansible_facts['distribution'] == "Ubuntu")
- include_tasks: debinstall.yml
  when: (ansible_facts['distribution'] == "Debian")
- include_tasks: centinstall.yml
  when: ansible_facts['distribution'] == "CentOS"
