---
- name: Install base packages for Vivumlab
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - cifs-utils
      - curl
      - gnupg-agent
      - git
      - htop
      - iftop
      - iotop
      - lsb-release
      - mosh
      - nfs-common
      - screen
      - software-properties-common
      - sudo
      - unattended-upgrades
      - vim
      - wget
      - whois
      - zsh
      - python3-virtualenv
      - python3-openssl
      - python3-setuptools
      - python3-passlib
      - python3-pip
    update_cache: yes
  tags:
    - dependencies
  become: yes

- name: Install Docker-py, and Wheel
  pip:
    name: "{{ item }}"
    executable: pip3
  loop:
    - docker
    - wheel
  become: yes

- name: Timezone - configure /etc/timezone
  copy:
    content: "{{ common_timezone | regex_replace('$', '\n') }}"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
  register: common_timezone_config

- name: Timezone - reconfigure tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: determine if snap is installed
  shell: "which snap"
  register: snap_installed
  failed_when: "False"
  ignore_errors: true

- name: Ensure Docker is not installed via Snap
  snap:
    name: docker
    state: absent
  when:
    - ansible_facts['distribution_major_version'] is version('16.04', '>=')
    - "'vivumlab' in group_names"
    - snap_installed.rc == 0
  become: yes
  ignore_errors: yes

- name: Remove older docker.io based packages
  apt:
    name:
      - docker
      - docker.io
      - containerd
      - runc
      - docker-engine
    state: absent
  become: yes
  when: "'vivumlab' in group_names"

- name: Add an Apt signing key for the Docker-ce Repo
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg
    state: present
    validate_certs: no
  become: yes
  when: "'vivumlab' in group_names"

- name: Add the Docker-ce Repo
  apt_repository:
    #repo: deb https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }} {{ ansible_facts['distribution_release'] | lower }} stable
    # The line above should works, but if you're not on Focal, will fail.
    # The line below forces ubuntu to add the FOCAL dist repo.
    repo: deb https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }} focal stable
    state: present
  become: yes
  when: "'vivumlab' in group_names"

- name: Install Docker and containerd
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  tags:
    - dependencies
  become: yes
  when: "'vivumlab' in group_names"

- name: Install Docker-compose
  pip:
    name: docker-compose
    executable: pip3
  become: yes
  when: "'vivumlab' in group_names"

- name: Start Docker service
  systemd:
    state: started
    daemon_reload: yes
    name: docker
  become: yes
  when: "'vivumlab' in group_names"

- name: Adding user to Docker group
  user:
    name: "{{ vlab_ssh_user }}"
    groups: docker
    append: true
  become: yes
  when: "'vivumlab' in group_names"
