---
- name: Make lazylibrarian directory.
  file:
    path: "{{ volumes_root }}/lazylibrarian"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy lazylibrarian docker-compose.yml file into place.
  template:
    src: docker-compose.lazylibrarian.yml.j2
    dest: "{{ volumes_root }}/lazylibrarian/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure lazylibrarian systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/lazylibrarian.service

- name: Start lazylibrarian
  systemd:
    name: lazylibrarian
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
