---
- name: Make snapdrop directory.
  file:
    path: "{{ volumes_root }}/snapdrop"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy snapdrop docker-compose.yml file into place.
  template:
    src: docker-compose.snapdrop.yml.j2
    dest: "{{ volumes_root }}/snapdrop/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure snapdrop systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/snapdrop.service
  become: yes

- name: Start snapdrop
  systemd:
    name: snapdrop
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
