---
- name: Make miniflux directory.
  file:
    path: "{{ volumes_root }}/miniflux"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy miniflux docker-compose.yml file into place.
  template:
    src: docker-compose.miniflux.yml.j2
    dest: "{{ volumes_root }}/miniflux/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure miniflux systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/miniflux.service

- name: Start miniflux
  systemd:
    name: miniflux
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
