---
- name: Make hedgedoc directory.
  file:
    path: "{{ volumes_root }}/hedgedoc"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy hedgedoc docker-compose.yml file into place.
  template:
    src: docker-compose.hedgedoc.yml.j2
    dest: "{{ volumes_root }}/hedgedoc/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: setup default user
  shell: >
    docker-compose -f {{ volumes_root }}/hedgedoc/docker-compose.yml run --rm app bin/manage_users
    --add {{ admin_email }} --pass "{{ default_password }}"
  args:
    chdir: "{{ volumes_root }}/hedgedoc"
  ignore_errors: true

- name: Configure hedgedoc systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/hedgedoc.service

- name: Start hedgedoc
  systemd:
    name: hedgedoc
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
