---
- name: Make plex directory.
  file:
    path: "{{ volumes_root }}/plex"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Create necessary folders, with appropriate permissions.
  file:
    path: "{{ volumes_root }}/plex/{{ item }}"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  with_items:
    - "config"
  become: yes

- name: Copy plex docker-compose.yml file into place.
  template:
    src: docker-compose.plex.yml.j2
    dest: "{{ volumes_root }}/plex/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
    trim_blocks: "no"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure plex systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/plex.service

- name: Start plex
  systemd:
    name: plex
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
