---
- name: Make syncthing directory.
  file:
    path: "{{ volumes_root }}/syncthing"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy syncthing docker-compose.yml file into place.
  template:
    src: docker-compose.syncthing.yml.j2
    dest: "{{ volumes_root }}/syncthing/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure syncthing systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/syncthing.service

- name: Start syncthing
  systemd:
    name: syncthing
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
