---
- name: Make bitwarden directory.
  file:
    path: "{{ volumes_root }}/bitwarden"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy bitwarden docker-compose.yml file into place.
  template:
    src: docker-compose.bitwarden.yml.j2
    dest: "{{ volumes_root }}/bitwarden/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes


- name: Configure bitwarden systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/bitwarden.service

- name: Start bitwarden
  systemd:
    name: bitwarden
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
