---
- name: Make trilium directory.
  file:
    path: "{{ volumes_root }}/trilium"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy trilium docker-compose.yml file into place.
  template:
    src: docker-compose.trilium.yml.j2
    dest: "{{ volumes_root }}/trilium/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure trilium systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/trilium.service

- name: Start trilium
  systemd:
    name: trilium
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
