---
- name: Make mylar directory.
  file:
    path: "{{ volumes_root }}/mylar"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy mylar docker-compose.yml file into place.
  template:
    src: docker-compose.mylar.yml.j2
    dest: "{{ volumes_root }}/mylar/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure mylar systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/mylar.service

- name: Start mylar
  systemd:
    name: mylar
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
