---
- name: Make grocy directory.
  file:
    path: "{{ volumes_root }}/grocy"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"

- name: Copy grocy docker-compose.yml file into place.
  template:
    src: docker-compose.grocy.yml.j2
    dest: "{{ volumes_root }}/grocy/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure grocy systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/grocy.service

- name: Start grocy
  systemd:
    name: grocy
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
