---
- name: Make wallabag directories.
  file:
    path: "{{ volumes_root }}/wallabag/{{ item }}"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  loop:
    - "data"
    - "images"
    - "db"
  become: yes

- name: Make wallabag DB directory.
  file:
    path: "{{ volumes_root }}/wallabag/db"
    state: directory

- name: Copy wallabag docker-compose.yml file into place.
  template:
    src: docker-compose.wallabag.yml.j2
    dest: "{{ volumes_root }}/wallabag/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure wallabag systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/wallabag.service

- name: Start wallabag
  systemd:
    name: wallabag
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
