---
- name: Make matterbridge directory.
  file:
    path: "{{ volumes_root }}/matterbridge"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy matterbridge docker-compose.yml file into place.
  template:
    src: docker-compose.matterbridge.yml.j2
    dest: "{{ volumes_root }}/matterbridge/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Create empty config file.
  file:
    path: "{{ volumes_root }}/matterbridge/matterbridge.toml"
    state: touch
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Configure matterbridge systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/matterbridge.service

- name: Start matterbridge
  systemd:
    name: matterbridge
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
