---
- name: Make homedash directory.
  file:
    path: "{{ volumes_root }}/homedash"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy homedash docker-compose.yml file into place.
  template:
    src: docker-compose.homedash.yml.j2
    dest: "{{ volumes_root }}/homedash/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure homedash systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/homedash.service

- name: Start homedash
  systemd:
    name: homedash
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
