name: Sanity check
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled

jobs:
  check_pr_milestone:
    runs-on: ubuntu-latest
    name: Sets status via label
    steps:
      - uses: cchantep/probot-pr-status-label@ghaction-1.0.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  lint-pr:
    runs-on: ubuntu-latest
    needs: check_pr_milestone
    name: Lint PR
    steps:
      - uses: amannn/action-semantic-pull-request@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.DE_PAT }}
        # Optionally you can configure which types are allowed.
        # Default: https://github.com/commitizen/conventional-commit-types
        # with:
        #   types: fix, feat
