name: Sanity check
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled

jobs:
  pr_wip_check:
    runs-on: ubuntu-latest
    name: WIP Check
    steps:
    - name: WIP Check
      uses: tim-actions/wip-check@master
      with:
        labels: '["do-not-merge", "wip", "rfc", ":hammer_and_wrench: WIP"]'
        keywords: '["WIP", "wip", "RFC", "rfc"]'
  lint-pr:
    runs-on: ubuntu-latest
    needs: pr_wip_check
    name: Lint PR
    steps:
      - uses: amannn/action-semantic-pull-request@v3.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.DE_PAT }}
        # Optionally, you can provide options for further constraints.
        with:
          # Configure additional validation for the subject based on a regex.
          # This example ensures the subject doesn't start with an uppercase character.
          subjectPattern: ^(?![A-Z]).+$
