name: "Lint Commit Messages"
on:
  push:
    branches:
      - dev
      - master

jobs:
  commitlint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2

      - name: Trigger next workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DE_PAT }}
          repository: VivumLab/VivumLab
          event-type: 04-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: Set final status check
        if: failure()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DE_PAT }}
          repository: VivumLab/VivumLab
          event-type: 07-final-status-check
          client-payload: '{"success": false}'
