name: "Publish to Registry"

on:
  push:
    tags: v[1-9]+.[0-9]+.[0-9]+
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00

jobs:
  publish-to-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: vivumlab/vivumlab
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
