name: "Mirror back to dev"

on:
  repository_dispatch:
    types: [06-mirror-back-to-dev]

jobs:
  mirror_job:
    runs-on: ubuntu-latest
    name: Mirror master branch to dev branch
    steps:
      - name: Mirror action step
        id: mirror
        uses: google/mirror-branch-action@v1.0
        with:
          github-token: ${{ secrets.DE_PAT }}
          source: 'master'
          dest: 'dev'
      - name: Trigger next workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DE_PAT }}
          repository: VivumLab/VivumLab
          event-type: 07-final-status-check
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: Set final status check
        if: failure()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DE_PAT }}
          repository: VivumLab/VivumLab
          event-type: 07-final-status-check
          client-payload: '{"success": false}'
