name: "Trigger release"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Mirror action step
        if: ${{ github.actor == 'denis-ev' || github.actor == 'voryzen' || github.actor == 'codefriar' }}
        id: mirror
        uses: google/mirror-branch-action@v1.0
        with:
          github-token: ${{ secrets.DE_PAT }}
          source: 'dev'
          dest: 'master'
