---
- name: Create required directories.
  file:
    path: "{{ volumes_root }}/docs/{{ item }}"
    state: directory
  loop:
    - website
    - website/docs
    - website/src
    - website/static

- name: Read Tor connection info
  shell: cat /var/lib/tor/http-onion/hostname
  register: tor_domain_file
  when: enable_tor

- name: Read Tor connection info
  shell: cat /var/lib/tor/ssh-onion/hostname
  register: tor_ssh_domain_file
  when: enable_tor

- name: Read vlab version
  shell: cat '{{ volumes_root }}/VERSION'
  register: current_version_file

- name: Copy docs root files into place
  copy:
    src: "{{ item }}"
    dest: "{{ volumes_root }}/docs/website/"
  with_fileglob: '{{ playbook_dir }}/website/*'

- name: Copy docs src folder into place
  copy:
    src: "{{ playbook_dir }}/website/src/"
    dest: "{{ volumes_root }}/docs/website/src/"

- name: Copy docs static folder into place
  copy:
    src: "{{ playbook_dir }}/website/static/"
    dest: "{{ volumes_root }}/docs/website/static/"

- name: Create directories for md files
  file:
    path: "{{ volumes_root }}/docs/website/docs/{{ item.path }}"
    state: directory
    mode: '{{ item.mode }}'
  with_filetree: website/docs/
  when: item.state == 'directory'

- name: Copy docs md files into place
  template:
    src: "{{ item.src }}"
    dest: "{{ volumes_root }}/docs/website/docs/{{ item.path }}"
  with_filetree: website/docs/
  when: item.state == 'file' and (item.path | basename | regex_search('(.md)'))

- name: Copy docs other files into place
  copy:
    src: "{{ item.src }}"
    dest: "{{ volumes_root }}/docs/website/docs/{{ item.path }}"
  with_filetree: website/docs/
  when: item.state == 'file' and (item.path | basename | regex_search('[^\.md]*$'))

- name: Copy CONTRIBUTING.md
  copy:
    src: "CONTRIBUTING.md"
    dest: "{{ volumes_root }}/docs/website/docs/CONTRIBUTING.md"

- name: Copy CHANGELOG.md
  copy:
    src: "CHANGELOG.md"
    dest: "{{ volumes_root }}/docs/website/docs/CHANGELOG.md"

- name: Copy docs docker-compose.yml file into place.
  template:
    src: docker-compose.docs.yml.j2
    dest: "{{ volumes_root }}/docs/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
    current_version: "{{ current_version_file.stdout | default ('latest') }}"

- name: Configure docs systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/docs.service

- name: Start docs
  systemd:
    name: docs
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
