---
- name: Create required directories.
  file:
    path: "{{ volumes_root }}/docs/{{ item }}"
    state: directory
  loop:
    - src

- name: Read Tor connection info
  shell: cat /var/lib/tor/http-onion/hostname
  register: tor_domain_file
  when: enable_tor

- name: Read Tor connection info
  shell: cat /var/lib/tor/ssh-onion/hostname
  register: tor_ssh_domain_file
  when: enable_tor

- name: Read vlab version
  shell: cat '{{ volumes_root }}/VERSION'
  register: current_version_file

- name: Clone Vivumlab repo
  git:
    repo: https://github.com/VivumLab/VivumLab.git
    dest: "{{ volumes_root }}/docs/src"
    version: master
    force: yes

- name: Copy docs md files into place
  template:
    src: "{{ item.src }}"
    dest: "{{ volumes_root }}/docs/src/docs/{{ item.path }}"
  with_filetree: docs/
  when: item.state == 'file' and (item.path | basename | regex_search('(.md)'))

- name: Copy docs other files into place
  file:
    src: "{{ item.src }}"
    dest: "{{ volumes_root }}/docs/src/docs/{{ item.path }}"
  with_filetree: docs/
  when: item.state == 'file' and (item.path | basename | regex_search('[^\.md]*$'))

- name: Copy docs docker-compose.yml file into place.
  template:
    src: docker-compose.docs.yml.j2
    dest: "{{ volumes_root }}/docs/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
    current_version: "{{ current_version_file.stdout | default ('latest') }}"

- name: Configure docs systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/docs.service

- name: Start docs
  systemd:
    name: docs
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
