---
- name: Make pihole directory.
  file:
    path: "{{ volumes_root }}/pihole"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  become: yes

- name: Copy pihole docker-compose.yml file into place.
  template:
    src: docker-compose.pihole.yml.j2
    dest: "{{ volumes_root }}/pihole/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Pull pihole docker images
  docker_compose:
    project_src: "{{ volumes_root}}/pihole"
    pull: yes
  ignore_errors: yes

- name: Configure pihole systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/pihole.service

- name: Stop systemd-resolve
  systemd:
    name: systemd-resolved
    enabled: no
    daemon-reload: no
    state: stopped
  become: yes

- name: Start pihole
  systemd:
    name: pihole
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
