---
- name: Make turtl directories.
  file:
    path: "{{ volumes_root }}/{{ item }}"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  with_items:
    - "turtl"
    - "turtl/uploads"
    - "turtl/db"
  become: yes

- name: Copy turtl docker-compose.yml file into place.
  template:
    src: docker-compose.turtl.yml.j2
    dest: "{{ volumes_root }}/turtl/docker-compose.yml"
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
  become: yes

- name: Configure turtl systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/turtl.service

- name: Start turtl
  systemd:
    name: turtl
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
